# events is required, but the defaults are fine
events { }

http {
  server {
    listen 80;

    # Requests starting with / go to the frontend
    location / {
      proxy_pass http://frontend:80;
    }

    # Requests starting with /api/ go to the backend
    location /api/ {
      proxy_pass http://backend:3001;
    }
  }
}
