services:
  app:
    image: todo-front
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile

  backend:
    image: todo-backend
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_prod_data:/data/db

  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_prod_data:/data

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app
      - backend

volumes:
  mongo_prod_data:
  redis_prod_data:
